import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Header from '../components/header/index'
import Footer from '../components/footer/index'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SHITTR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SHITTR
        </h1>
        <div className={styles.grid}>
          <Link href="/map">
            <a>
              <h2>Map &rarr;</h2>
              <p>Find your nearest quality releif</p>
            </a>
          </Link>  
        </div>
      </main>
      <Footer />
    </div>
  )
}
