import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import LogButton from '../components/logButton'

export default function Home() {
  const { data: session } = useSession()
  return (
    <div className={styles.container}>
      <Head>
        <title>SHITTR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LogButton
        session={session}
      />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SHITTR
        </h1>
        <div className={styles.grid}>
          <Link href="/map">
            <a>
              <h2>Map &rarr;</h2>
              <p>Find your nearest quality releif</p>
            </a>
          </Link>  
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
